/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Media = Uint8Array;
export type MessageId = bigint;
export type Nickname = string;
export interface PublicMessage {
  'media' : [] | [Media],
  'content' : string,
  'nickname' : Nickname,
  'messageId' : MessageId,
  'userId' : UserId,
  'timestamp' : Time,
  'replyTo' : [] | [MessageId],
  'roomId' : RoomId,
  'reactions' : Array<Reaction>,
}
export interface Reaction { 'userId' : UserId, 'emoji' : string }
export interface Room { 'name' : string, 'roomId' : RoomId }
export type RoomId = string;
export type Time = bigint;
export type UserId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createRoom' : ActorMethod<[RoomId, string], undefined>,
  'deleteMessage' : ActorMethod<[UserId, RoomId, MessageId], undefined>,
  'editMessage' : ActorMethod<
    [UserId, RoomId, MessageId, string],
    PublicMessage
  >,
  'getMessages' : ActorMethod<[RoomId, bigint, bigint], Array<PublicMessage>>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'postMessage' : ActorMethod<
    [UserId, RoomId, string, [] | [Media], [] | [MessageId]],
    PublicMessage
  >,
  'reactToMessage' : ActorMethod<
    [UserId, RoomId, MessageId, string],
    PublicMessage
  >,
  'setNickname' : ActorMethod<[UserId, string], undefined>,
  'validateRoom' : ActorMethod<[RoomId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];