/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomId = IDL.Text;
export const UserId = IDL.Text;
export const MessageId = IDL.Nat;
export const Media = IDL.Vec(IDL.Nat8);
export const Nickname = IDL.Text;
export const Time = IDL.Int;
export const Reaction = IDL.Record({ 'userId' : UserId, 'emoji' : IDL.Text });
export const PublicMessage = IDL.Record({
  'media' : IDL.Opt(Media),
  'content' : IDL.Text,
  'nickname' : Nickname,
  'messageId' : MessageId,
  'userId' : UserId,
  'timestamp' : Time,
  'replyTo' : IDL.Opt(MessageId),
  'roomId' : RoomId,
  'reactions' : IDL.Vec(Reaction),
});
export const Room = IDL.Record({ 'name' : IDL.Text, 'roomId' : RoomId });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createRoom' : IDL.Func([RoomId, IDL.Text], [], []),
  'deleteMessage' : IDL.Func([UserId, RoomId, MessageId], [], []),
  'editMessage' : IDL.Func(
      [UserId, RoomId, MessageId, IDL.Text],
      [PublicMessage],
      [],
    ),
  'getMessages' : IDL.Func(
      [RoomId, IDL.Nat, IDL.Nat],
      [IDL.Vec(PublicMessage)],
      ['query'],
    ),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'postMessage' : IDL.Func(
      [UserId, RoomId, IDL.Text, IDL.Opt(Media), IDL.Opt(MessageId)],
      [PublicMessage],
      [],
    ),
  'reactToMessage' : IDL.Func(
      [UserId, RoomId, MessageId, IDL.Text],
      [PublicMessage],
      [],
    ),
  'setNickname' : IDL.Func([UserId, IDL.Text], [], []),
  'validateRoom' : IDL.Func([RoomId], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomId = IDL.Text;
  const UserId = IDL.Text;
  const MessageId = IDL.Nat;
  const Media = IDL.Vec(IDL.Nat8);
  const Nickname = IDL.Text;
  const Time = IDL.Int;
  const Reaction = IDL.Record({ 'userId' : UserId, 'emoji' : IDL.Text });
  const PublicMessage = IDL.Record({
    'media' : IDL.Opt(Media),
    'content' : IDL.Text,
    'nickname' : Nickname,
    'messageId' : MessageId,
    'userId' : UserId,
    'timestamp' : Time,
    'replyTo' : IDL.Opt(MessageId),
    'roomId' : RoomId,
    'reactions' : IDL.Vec(Reaction),
  });
  const Room = IDL.Record({ 'name' : IDL.Text, 'roomId' : RoomId });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createRoom' : IDL.Func([RoomId, IDL.Text], [], []),
    'deleteMessage' : IDL.Func([UserId, RoomId, MessageId], [], []),
    'editMessage' : IDL.Func(
        [UserId, RoomId, MessageId, IDL.Text],
        [PublicMessage],
        [],
      ),
    'getMessages' : IDL.Func(
        [RoomId, IDL.Nat, IDL.Nat],
        [IDL.Vec(PublicMessage)],
        ['query'],
      ),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'postMessage' : IDL.Func(
        [UserId, RoomId, IDL.Text, IDL.Opt(Media), IDL.Opt(MessageId)],
        [PublicMessage],
        [],
      ),
    'reactToMessage' : IDL.Func(
        [UserId, RoomId, MessageId, IDL.Text],
        [PublicMessage],
        [],
      ),
    'setNickname' : IDL.Func([UserId, IDL.Text], [], []),
    'validateRoom' : IDL.Func([RoomId], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };